DEFAULT_SHEET_NAME = "데일리매출"

DEFAULT_CASH_CELL = "M5"
DEFAULT_CARD_CELL = "M6"
DEFAULT_TRANSFER_CELL = "M7"
DEFAULT_TOTAL_CELL = "M8"

APP_VERSION = "1.3.6"
APP_NAME = f"리와인드 휘트니스 전산 자동화 프로그램 v{APP_VERSION}"
WINDOW_WIDTH = 500
WINDOW_HEIGHT = 760
