DEFAULT_SHEET_NAME = "데일리매출"

DEFAULT_CASH_CELL = "M5"
DEFAULT_CARD_CELL = "M6"
DEFAULT_TRANSFER_CELL = "M7"
DEFAULT_TOTAL_CELL = "M8"

APP_NAME = "리와인드 휘트니스 전산 자동화 프로그램"
WINDOW_WIDTH = 900
WINDOW_HEIGHT = 600